# Generated by Django 3.0.2 on 2020-04-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('biddingId', models.AutoField(primary_key=True, serialize=False)),
                ('biddingPrice', models.IntegerField()),
            ],
        ),
    ]
