# Generated by Django 3.0.2 on 2020-04-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='biddingWinner',
            field=models.CharField(default='', max_length=60),
        ),
    ]
