# Generated by Django 3.0.2 on 2020-04-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('auctionId', models.AutoField(primary_key=True, serialize=False)),
                ('auctionBiddingPrice', models.IntegerField()),
                ('auctionStatus', models.CharField(choices=[('1', 'Open'), ('2', 'Completed')], default='1', max_length=20)),
                ('auctionWinner', models.CharField(max_length=60)),
            ],
        ),
    ]
