# Generated by Django 3.0.2 on 2020-04-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('auctionId', models.AutoField(primary_key=True, serialize=False)),
                ('auctionBiddingPrice', models.IntegerField()),
                ('auctionStatus', models.CharField(choices=[('1', 'Open'), ('2', 'Completed')], default='1', max_length=20)),
                ('auctionWinner', models.CharField(max_length=60)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Items')),
            ],
        ),
    ]
