# Generated by Django 3.0.2 on 2020-04-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auctions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemHistory',
            fields=[
                ('ItemId', models.AutoField(primary_key=True, serialize=False)),
                ('itemTitle', models.CharField(max_length=60)),
                ('finalPrice', models.IntegerField()),
                ('itemDescription', models.CharField(max_length=60)),
                ('itemBoughtFrom', models.CharField(max_length=60)),
            ],
        ),
    ]
