# Generated by Django 3.0.2 on 2020-04-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='userBidding',
            field=models.CharField(default='', max_length=60),
        ),
    ]
