# Generated by Django 3.0.2 on 2020-04-06 22:59

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auctions_userbidding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='itemId',
        ),
    ]
