# Generated by Django 3.0.2 on 2020-04-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20200406_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='itemTitle',
            field=models.CharField(default='', max_length=60),
        ),
    ]
